engines:
  duplications:
    enabled: true
    config:
      languages:
        #mass_threshold: 30
        - javascript
  eslint:
    enabled: true
    checks:
      comma-dangle:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
    - "server"
languages:
  JavaScript: true
exclude_paths:
- "coverage/"
- "server/helpers/"
- "server/test/"
- .gitignore
- .eslintrc
- .travis.yml
- .sequelizerc
- "server/config/"
- "server/models/"
- "server/seeders/"
- "./client/"
- "/server"
- "/server/"