sudo: required
dist: trusty
language: node_js

node_js:
  - 6

services:
  - postgresql

before_script:
  - psql -c 'drop database if exists cp3_test;' -U postgres
  - psql -c 'create database testSystem;' -U postgres
  - npm run migrate:test

script:
  - npm run test

after_script: npm run coveralls

addons:
  postgresql :"9.3"