export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_AVAILABLE_DOCUMENT = 'SET_AVAILABLE_DOCUMENT';
export const CREATE_DOCUMENT_MESSAGE = 'CREATE_DOCUMENT_MESSAGE';
export const UPDATE_DOCUMENT_MESSAGE = 'UPDATE_DOCUMENT_MESSAGE';
export const SEARCH_DOCUMENT_MESSAGE = 'SEARCH_DOCUMENT_MESSAGE';
export const SET_SINGLE_DOCUMENT = 'SET_SINGLE_DOCUMENT';
export const SET_USER_DOCUMENT = 'SET_USER_DOCUMENT';
export const SET_UPDATE_USER = 'SET_UPDATE_USER';
export const SET_CREATE_USER = 'SET_CREATE_USER';
export const SET_GET_USER = 'SET_GET_USER';
export const CREATE_ROLE = 'CREATE_ROLE';
export const GET_ROLES = 'GET_ROLES';
export const DELETE_ROLES = 'DELETE_ROLES';
export const UPDATE_ROLES = 'UPDATE_ROLES';
export const GET_USERS = 'GET_USERS';
export const CREATE_USERS = 'CREATE_USERS';
export const DELETE_USER = 'DELETE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const SET_SINGLE_USER = 'SET_SINGLE_USER';
export const UPDATE_USERS = 'UPDATE_USERS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SEARCH_DOCUMENT = 'SEARCH_DOCUMENT';
export const SEARCH_USERS = 'SEARCH_USERS';
export const USER_DOCUMENT = 'USER_DOCUMENT';
export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
export const LOAD_DOCUMENTS = 'LOAD_DOCUMENTS';
export const GET_SINGLE_DOCUMENT = 'GET_SINGLE_DOCUMENT';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT';
export const SEARCH_MY_DOCUMENT = 'SEARCH_MY_DOCUMENT';




